language: node_js

node_js:
  - '6.0.0'

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ba35fae32bdd8f239026
    on_success: change
    on_failure: always
    on_start: never

install:
  - npm install -g gulp-cli
  - npm install

script:
  - npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)
