codecov:
  notify:
    require_ci_to_pass: true

comment:
  behavior: default
  layout: header, diff
  require_changes: false

coverage:
  precision: 2
  range:
  - 70.0
  - 100.0
  round: down
  status:
    changes: false
    patch: true
    project: true
  notify:
    gitter:
      default:
        url: https://webhooks.gitter.im/e/18d3e2a6d134a4c3f823
        branches:
          - master
        threshold: null
    slack:
      default:
        url:  https://hooks.slack.com/services/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
        branches:
          - master
        threshold: null

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
    enable_partials: false
